In [1]:
###import data using pandas
import pandas as pd
import pandas as pd
import numpy as np
from sklearn.datasets import load_wine

In [2]:
df=pd.read_csv("./raw/monroe-county-crash-data2003-to-2015.csv", encoding= 'unicode_escape')
df.head()

,Master Record Number,Year,Month,Day,Weekend?,Hour,Collision Type,Injury Type,Primary Factor,Reported_Location,Latitude,Longitude
0,902363382,2015,1,5,Weekday,0.0,2-Car,No injury/unknown,OTHER (DRIVER) - EXPLAIN IN NARRATIVE,1ST & FESS,39.159207,-86.525874
1,902364268,2015,1,6,Weekday,1500.0,2-Car,No injury/unknown,FOLLOWING TOO CLOSELY,2ND & COLLEGE,39.161440,-86.534848
2,902364412,2015,1,6,Weekend,2300.0,2-Car,Non-incapacitating,DISREGARD SIGNAL/REG SIGN,BASSWOOD & BLOOMFIELD,39.149780,-86.568890
3,902364551,2015,1,7,Weekend,900.0,2-Car,Non-incapacitating,FAILURE TO YIELD RIGHT OF WAY,GATES & JACOBS,39.165655,-86.575956
4,902364615,2015,1,7,Weekend,1100.0,2-Car,No injury/unknown,FAILURE TO YIELD RIGHT OF WAY,W 3RD,39.164848,-86.579625

In [3]:
df.dropna()
df = (
    df
    .assign(Weekend=lambda x: x["Weekend?"]=="Weekend")
    .assign(DateTime=lambda x:pd.to_datetime(x["Year"] + x["Month"] + x["Hour"]))
    .rename(columns={"Injury Type":"Type"})
    .dropna()
    .drop(['Weekend?',"Year","Month","Hour"],axis=1)
    .sort_values("Master Record Number", ascending=True)
    .reset_index()
)
df.to_csv("./processed/monroe-county-crash-data2003-to-2015.csv")
df

,index,Master Record Number,Day,Collision Type,Type,Primary Factor,Reported_Location,Latitude,Longitude,Weekend,DateTime
0,52422,14705,4,2-Car,No injury/unknown,PEDESTRIAN ACTION,CURRY PIKE & HERITAGE,39.153504,-86.582720,False,1970-01-01 00:00:00.000002905
1,52617,14707,5,Moped/Motorcycle,No injury/unknown,OTHER (DRIVER) - EXPLAIN IN NARRATIVE,MILLER & WALNUT ST,39.146944,-86.532544,False,1970-01-01 00:00:00.000002909
2,52752,14709,3,2-Car,No injury/unknown,FOLLOWING TOO CLOSELY,TAPP & US37,39.137040,-86.572896,False,1970-01-01 00:00:00.000002813
3,52241,14821,2,2-Car,Non-incapacitating,DISREGARD SIGNAL/REG SIGN,1ST & ROGERS ST,39.159504,-86.538592,False,1970-01-01 00:00:00.000003404
4,53349,14843,5,2-Car,No injury/unknown,OTHER (DRIVER) - EXPLAIN IN NARRATIVE,45 46 BYPASS & E 10TH,0.000000,0.000000,False,1970-01-01 00:00:00.000004305
...,...,...,...,...,...,...,...,...,...,...,...
52577,4307,902607777,3,1-Car,No injury/unknown,OTHER (DRIVER) - EXPLAIN IN NARRATIVE,N DANIELS,39.169361,-86.596748,False,1970-01-01 00:00:00.000003627
52578,4308,902609951,5,2-Car,No injury/unknown,OTHER (VEHICLE) - EXPLAIN IN NARRATIVE,SUMMIT & W 13TH,39.175152,-86.548048,False,1970-01-01 00:00:00.000003527
52579,4309,902616058,4,2-Car,No injury/unknown,UNSAFE BACKING,RAUBS,39.229901,-86.635728,False,1970-01-01 00:00:00.000004127
52580,4310,902623025,4,1-Car,No injury/unknown,ANIMAL/OBJECT IN ROADWAY,BURMA & SR37,39.313599,-86.511727,False,1970-01-01 00:00:00.000002927
52581,4311,902627122,3,2-Car,No injury/unknown,ANIMAL/OBJECT IN ROADWAY,INGRAM & SR37S,39.097340,-86.595642,False,1970-01-01 00:00:00.000003427

In [4]:
df["Type"].unique()

array(['No injury/unknown', 'Non-incapacitating', 'Incapacitating',
       'Fatal'], dtype=object)

In [5]:
def load_and_process(url_or_path_to_csv_file):
    df=pd.read_csv(url_or_path_to_csv_file, encoding= 'unicode_escape')

    df.dropna()
    df = (
        df
        .assign(Weekend=lambda x: x["Weekend?"]=="Weekend")
        .assign(DateTime=lambda x:pd.to_datetime(x["Year"] + x["Month"] + x["Hour"]))
        .rename(columns={"Injury Type":"Type"})
        .dropna()
        .drop(['Weekend?',"Year","Month","Hour"],axis=1)
        .sort_values("Master Record Number", ascending=True)
        .reset_index()
    )
    df.to_csv("./processed/monroe-county-crash-data2003-to-2015.csv")
    
    return df

In [7]:
df.columns

Index(['index', 'Master Record Number', 'Day', 'Collision Type', 'Type',
       'Primary Factor', 'Reported_Location', 'Latitude', 'Longitude',
       'Weekend', 'DateTime'],
      dtype='object')